name: flutter_wordle
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_confetti: ^0.5.1
  freezed_annotation: ^3.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/launcher_icons/icon.png"
  android: "ic_launcher"
  ios: true
  image_path_ios_dark_transparent: "assets/launcher_icons/icon_transparent.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon.png"
