include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    file_names: false
    flutter_style_todos: false
    public_member_api_docs: false
    one_member_abstracts: false
    avoid_print: false
