name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  drift: ^2.26.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.7.5

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
